### ISSUE TITLE
Problems loading CyVerse Phavu data into a mine

### ISSUE THREAD

**Issue by sammyjava** [LegumeFederationDataStore/about_the_data_store#24]
I've got a mine builder that sources CyVerse data files, which can be used as a consistency checker. So, here's the problems with the current batch of **genome v2** files under
`/iplant/home/shared/Legume_Federation/Phaseolus_vulgaris`:

1. Chromosome FASTA:
`G19833.gnm2.fC0g/phavu.G19833.gnm2.fC0g.fa`
- **chromosome names** "Chr01", etc. are undesirable for consistency with external data sources (like, say, PvGEA).
- **scaffold names** like "scaffold_743" ARE acceptable IF _made standard_ so that the loader can load scaffold_N as Supercontig objects rather than Chromosome objects. (Via a hack in the FASTA loader.) 

2. Genes/Exons FASTA:
`G19833.gnm2.ann1.PB8d/phavu.G19833.gnm2.ann1.PB8d.gene_exons.gff3`
- **chromosome names** like "Chr01", etc. see above.

3. Protein FASTA:
`G19833.gnm2.ann1.PB8d/phavu.G19833.gnm2.ann1.PB8d.protein.fa`
- **proteins have suffix ".p"** (e.g. Phvul.010G044100.1.p) which prevents them from being associated with genes by the post-processor. They load as stranded objects.

4. Blair SNP markers GFF (mapped to v1, actually):
`mixed.map1.blair.7PMp/phavu.mixed.map1.blair.7PMp.map.gff3`
- **chromosome names** are "Pv01", etc. This creates separate chromosomes from the genome loaded above. This is preferable naming, though, since PvNN is used in many external sources like PvGEA.
- **SNP marker names** like TOG894002_618 differ from below, which prevents SNP markers being merged into single records with both genetic and genomic position.

5. Blair SNP markers CMap:
`mixed.map1.blair.7PMp/phavu.mixed.map1.blair.7PMp.cmap.txt`
- **linkage groups names** are "Pv01", etc. This is fine, since they're linkage groups, not chromosomes, but still inconsistent with genomic names.
**SNP marker names** like "Pv_TOG894002" differ from above, resulting in duplicate markers: one with genomic position and one with genetic position.

_Recommendations_
1. Drop ".p" from protein names
2. Rename chromosomes to a consistent name in all FASTAs and GFFs. 
3. Use consistent naming for SNP markers from the Blair set. I prefer "Pv_TOG894002" style, since the extra numerical suffix doesn't seem to play a role. But also see below about LG position inconsistency.

**Comment by sammyjava** [comment]
Also I notice an inconsistency between the LG position in the Note field of the GFF and the actual LG position recorded in the CMap file. For example,
```
beanmine=> select primaryidentifier,note,sequenceid,chromosomeid,intermine_position from geneticmarker,geneticmarkerlinkagegrouppositions,linkagegroupposition where geneticmarker.id=geneticmarkerlinkagegrouppositions.geneticmarker and geneticmarkerlinkagegrouppositions.linkagegrouppositions=linkagegroupposition.id order by primaryidentifier limit 1;
 primaryidentifier | note | sequenceid | chromosomeid | intermine_position 
-------------------+------+------------+--------------+--------------------
 Pv_TOG894002      |      |            |              |               55.6
(1 row)

beanmine=> select primaryidentifier,note,sequenceid,chromosomeid from geneticmarker where chromosomeid is not null order by primaryidentifier limit 1;
 primaryidentifier |     note     | sequenceid | chromosomeid 
-------------------+--------------+------------+--------------
 TOG894002_618     | LG01 cM 49.4 |            |     12000001
```

**Comment by adf-ncgr** [comment]
to my way of thinking both Chr01 and scaffold_743 are undesirable in a multi-organism mine. I think prefixing both with `phavu.` or `phavu.G19833.` is preferable to altering Chr01 to Pv01 and doing something else to disambiguate scaffold (aka supercontig) naming. But you knew that already. I will also point out that two letter species codes are more fragile than five letter codes; think "Lupinus angustifolius" and "Lupinus albus"; two actual species in the datastore, though only the former has a genome at this time- note that although its GBrowse lives under https://legumeinfo.org/genomes/gbrowse/La1.0 its chromosomes are named in it as NLL-01 etc
short for "narrow-leaved lupin", which I believe is exactly how they came in. In the chado these are lupan.NLL-01 because we only presume to add prefixes, but otherwise leave as is.

**Comment by sammyjava** [comment]
I'm not touching HOW to name things here, really. InterMine doesn't really care. This issue is about self-consistency. If the files load into a merged mine, then they "work." I've just put in 2 cents where appropriate, but this issue is solved if the Phavu set loads a merged mine.

**Comment by adf-ncgr** [comment]
I thought you were touching how to name things, most explicitly in your recommendations. So I added my 2c. 
Recommendation 1 is already enshired in our standard:
https://github.com/LegumeFederation/datastore/blob/master/metadata/about_the_data_repository.md#miscellaneous-data-standards
so we just need to make it so in the files.

I am disagreeing with your recommendation 2; but if that becomes the will of the masses, then I anticipate that this style of naming will propagate into all of our systems, including chado. Because it's not all just about the mines...

**Comment by sammyjava** [comment]
Yeah, sorry, I've backed off from recommending any naming here, that's another topic, which results in nothing ever actually happening because we seem totally frozen up on that topic. This issue is strictly about self-consistency so we can load a mine. I want it to be a standalone issue, because I'd like to be able to load a Phavu mine from unedited datastore files. Which is separate from other datastore issues. Plus, mine-loading is a nice consistency check that just requires a single command.

**Comment by adf-ncgr** [comment]
> "Chr01", etc. are undesirable for consistency with external data sources (like, say, PvGEA).

phytozome uses Chr01 and they are the origin of this assembly
https://phytozome.jgi.doe.gov/jbrowse/index.html?data=genomes%2FPvulgaris%2F&loc=Chr08%3A1..100000&tracks=Transcripts%2CAlt_Transcripts%2CPASA_assembly%2CBlastx_protein%2CBlatx_FabidaeGrape&highlight=

I don't think we'll be able to achieve consistency with all external data sources, because they are not consistent. For example, if EnsemblPlants had Phavu I bet they would call this chromosome "1" as they do with Glyma: 
http://plants.ensembl.org/Glycine_max/Location/View?r=1%3A7801001-7811000;site=ensemblthis

If you can enunciate a rule that makes more sense to me than "they who built it have the right to name it", I am prepared to consider it.

regarding map files, I agree that this is wild west territory that needs to be tamed....

**Comment by sammyjava** [comment]
I'll add that a load of the v1 genome and annotation does NOT have the protein.p problem in 3 above. The v1 protein FASTA has gene.1 names, which match up with the genes. So that is strictly a v2 problem for the moment.

**Comment by jd-campbell** [comment]
@sammyjava - Any new developments with this issue? I am going to start looking into this now.

**Comment by sammyjava** [comment]
Good question. I think some of it has been fixed. When the datastore comes back up (it's throwing a Connection Refused at the moment) I'll refresh the files and give it another spin.

**Comment by jd-campbell** [comment]
**File status in LegumeInfo DataStore**

1.  Chromosome FASTA: G19833.gnm2.fC0g/phavu.G19833.gnm2.fC0g.fa (phavu.G19833.gnm2.fC0g.genome_main.fna)

chromosome names "Chr01", etc. are undesirable for consistency with external data sources (like, say, PvGEA).  
**STATUS**: _>phavu.G19833.gnm2.Chr10_

scaffold names like "scaffold_743" ARE acceptable IF made standard so that the loader can load scaffold_N as Supercontig objects rather than Chromosome objects. (Via a hack in the FASTA loader.) 
**STATUS**: _>phavu.G19833.gnm2.scaffold_1248_

2.  Genes/Exons FASTA:
G19833.gnm2.ann1.PB8d/phavu.G19833.gnm2.ann1.PB8d.gene_exons.gff3
**STATUS**: _*.gene_exons.gff3 file no longer exists_

3. Protein FASTA:
G19833.gnm2.ann1.PB8d/phavu.G19833.gnm2.ann1.PB8d.protein.fa
proteins have suffix ".p" (e.g. Phvul.010G044100.1.p) which prevents them from being associated with genes by the post-processor. They load as stranded objects.
**STATUS:** _".p" still present in name_

4. Blair SNP markers GFF (mapped to v1, actually):
mixed.map1.blair.7PMp/phavu.mixed.map1.blair.7PMp.map.gff3
chromosome names are "Pv01", etc. This creates separate chromosomes from the genome loaded above. This is preferable naming, though, since PvNN is used in many external sources like PvGEA.
**STATUS:** _Still Pv##_

SNP marker names like TOG894002_618 differ from below, which prevents SNP markers being merged into single records with both genetic and genomic position.
**STATUS**: _Still needs to be fixed_

**Comment by jd-campbell** [comment]
@cann0010 @adf-ncgr  I have three separate RFO I want to bring your attention. If I hear no objections by Tuesday May 1st. I will make the mentioned changes. 

RFO: Change the protein name by removing the ".p" (e.g. Phvul.010G044100.1.p) in this file G19833.gnm2.ann1.PB8d/phavu.G19833.gnm2.ann1.PB8d.protein.fa
**Reason:** @sammyjava ran into problems with the Intermine builder the ".p"  prevents the proteins from being associated with genes by the post-processor. They load as stranded objects.

RFO: Change the chromosome names by replacing 'Pv' with "phavu.G19833.gnm1.Chr" in this file: mixed.map1.7PMp/phavu.mixed.map1.7PMp.map.gff3
**Reason:** Sam ran into problems with the Intermine builder that sources CyVerse data files the "Pv01" name creates separate chromosomes from the genome. 

RFO: Change the SNP marker names by adding "Pv_" to the beginning of the SNP name in this file: mixed.map1.7PMp/phavu.mixed.map1.7PMp.map.gff3
**Reason:**  The SNP maker names in the map file do not have the "Pv_" prefix but in the Cmap file the SNP markers do have the "Pv_" prefix

**Comment by cann0010** [comment]
All three RFOs look reasonable to me.

**Comment by adf-ncgr** [comment]
not only do I not object, I heartily endorse!

**Comment by jd-campbell** [comment]
- [ ] _G19833.gnm2.ann1.PB8d/phavu.G19833.gnm2.ann1.PB8d.protein.fa_ - remove ".p"
- [ ] _mixed.map1.7PMp/phavu.mixed.map1.7PMp.map.gff3_ - replace 'Pv' with "phavu.G19833.gnm1.Chr"
- [ ] _mixed.map1.7PMp/phavu.mixed.map1.7PMp.map.gff3_ - add "Pv_" to the beginning of the SNP name

**Comment by sammyjava** [comment]
Loaded, you can view it on: http://fisher.ncgr.org:50000/beanmine/begin.do

**Looks good for chromosome loading now:**

DB identifier | Length
--------------- | ---------
phavu.G19833.gnm1.Chr01 | 52205531
phavu.G19833.gnm1.Chr02 | 49040938
phavu.G19833.gnm1.Chr03 | 52284309
phavu.G19833.gnm1.Chr04 | 45960019
phavu.G19833.gnm1.Chr05 | 40819286
phavu.G19833.gnm1.Chr06 | 31977256
phavu.G19833.gnm1.Chr07 | 51758522
phavu.G19833.gnm1.Chr08 | 59662532
phavu.G19833.gnm1.Chr09 | 37469608
phavu.G19833.gnm1.Chr10 | 43275151
phavu.G19833.gnm1.Chr11 | 50367376 

Genes get loaded with the appropriate yuck:

DB identifier | Length | Symbol
--------------- | --------- | ----------
phavu.G19833.gnm1.ann1.Phvul.010G162100 | 2179 | phavu.Phvul.010G162100 

***1. A SEARCH on Phvul.010G162100 RETURNS NO RESULTS, because there is nothing in the database with that primaryIdentifier or secondaryIdentifier or symbol.*** (IM's Lucene search is for case-insensitive but otherwise exact matches.)

Proteins get loaded with **non-yucky** names:

DB identifier | Length
--------------- | ---------
Phvul.010G162100.1 | 594 

This means that a SEARCH on Phvul.010G162100.1 DOES RETURN RESULTS, because there is a protein with that name in the DB.

***2. Because genes and proteins have different names, PROTEINS and GENES DO NOT GET LINKED in post-processing.***

mRNAs get loaded with yucky names:

DB identifier | Length | Symbol
--------------- | --------- | ----------
phavu.G19833.gnm1.ann1.Phvul.010G162100.1 |	2179 | phavu.Phvul.010G162100.1 

***3. Because proteins and mRNAs have different names,  PROTEINS and mRNAs DO NOT GET LINKED in post-processing.***

There are no exons.

CDSes get loaded with yucky names:

DB identifier | Length | Symbol
--------------- | --------- | ----------
phavu.G19833.gnm1.ann1.Phvul.010G162100.1.v1.0.CDS.1 | 235 | phavu.Phvul.010G162100.1.v1.0.CDS.1 
Phavu.G19833.gnm1.ann1.Phvul.010G162100.1.v1.0.CDS.2 | 78 | phavu.Phvul.010G162100.1.v1.0.CDS.2
phavu.G19833.gnm1.ann1.Phvul.010G162100.1.v1.0.CDS.3 | 1469 | phavu.Phvul.010G162100.1.v1.0.CDS.3 

**The post-processing of overlapping features works fine, since that's just a question of having the same chromosome.** So, this gene has the mRNA, three CDSes and a FivePrimeUTR associated with it via genomic positions, but not through name-matching (which would be listed as "child features"):

http://fisher.ncgr.org:50000/beanmine/report.do?id=5542204

**Comment by adf-ncgr** [comment]
thanks guys. My firmly held belief is that the transcript and protein fastas OUGHT to have the
yucky ids as well, though we are a bit behind on actually getting those standards in place. I am assuming that the reason you get mRNAs linked to genes but not proteins is because the mRNA are
explicit in the gff (which is fully yuckified) but the proteins are only implicit there and are likely getting picked up from the protein fasta instead. Should I issue an RFO to yuckify all fastas?

**Comment by sammyjava** [comment]
Actually genes and mRNAs are NOT "directly" linked because that normally happens in the chado loader. So I'll add a post-processor that spins through genes and mRNAs, matching G with G.n where n is a small integer. Yes, the naming is fine for that process:

Gene

DB identifier | Length | Symbol
-- | -- | --
phavu.G19833.gnm1.ann1.Phvul.010G162100 | 2179 | phavu.Phvul.010G162100

mRNA

DB identifier | Length | Symbol
-- | -- | --
phavu.G19833.gnm1.ann1.Phvul.010G162100.1 | 2179 | phavu.Phvul.010G162100.1

**Comment by sammyjava** [comment]
And yes, if we want to associate proteins and transcripts with ANYTHING else in the directories, we need to yuckify the FASTAs. Name matching matters.

**Comment by sammyjava** [comment]
FYI I load mRNAs from the GFF, not a FASTA, but there's no specific reason for that. The sequence post-processor figures out the sequences from the genomic range so I presume I'd wind up with the same thing, unless the transcripts are actually distinct data from the genome.

**Comment by sammyjava** [comment]
And, finally, yes, I load proteins from their FASTA since they have amino acid residues and there is no post-processor in IM that will figure that out from the nucleic acid residues (that I know of).

**Comment by sammyjava** [comment]
OK one more: I *do* think that not being able to type a "normal" gene name like Phvul.010G162100 and get a result is poor service to users. I guess if we stick with all this I'll have to relax the Lucene search to include substrings, which could make it really go nuts. The problem is simply the "phavu." prefix, since we do load phavu.Phvul.010G162100 as "symbol" (which it isn't), and symbol is indexed for searching.

Alternatively I can do a post-load hack (like I do so often with chado data) to strip the "phavu." from the symbol attribute.

**Comment by sammyjava** [comment]
FWIW, I've added a new post-processor that links genes to mRNAs based on identifier. The current BeanMine-DS has that implemented, genes show a child feature which is an mRNA.

**1 Child Features** 

DB identifier | Length | Chromosome Location
-- | -- | --
phavu.G19833.gnm1.ann1.Phvul.010G162100.1 | 2179 | phavu.G19833.gnm1.Chr10: 42978799-42980977

**Comment by adf-ncgr** [comment]
@sammyjava : closeable?

**Comment by sammyjava** [comment]
Yeah I think it's well behind the current state of the datastore, and I'm using the LIS datastore now.
