### ISSUE TITLE
Create naming convention for genotype data files

### ISSUE THREAD

**Issue by ekcannon** [LegumeFederationDataStore/about_the_data_store#45]
I propose allowing two types of files: hapmap and flapjack. Initial proposal:
**[species_or_genus].mixed.[population?].genotype.[key].[file_type].[hap|flapjack]**

Example:
**arachis.mixed.minicore.genotype.Z0Z0.hapmap.hap
arachis.mixed.minicore.genotype.Z0Z0.flapjack.flapjack**

Is the [file_type] field required? It's a bit redundant for the flapjack file. Are there different (standardized) types of genotype? E.g marker vs SNP vs ? Or are they always SNP-based?

Requesting comments from @adf-ncgr, @cann0010, and @jd-campbell (and anyone else who wants to chime in.)

**Comment by cann0010** [comment]
Mentioning @avbrown1 , who is processing lots of these collections for soybean.
See the ".div" collections here: https://soybase.org/data/public/Glycine_max/
So far, it looks like we are signifying the type with the suffix: .vcf or .hmp
To find these files using the h5ai interface, navigate to https://soybase.org/data/public/Glycine_max/
and then use the magnifying-glass icon (upper left) to search for hmp or vcf

**Comment by ekcannon** [comment]
Looks like the convention for the soybean genotype data is:
[species][genotype][assembly].div[#].[key].[data_type].[vcf|hmp|flapjack]

But I think the mini core genotype data is based on a sort of pseudo-assembly of aradu+araip, so how would that be represented? And should ".flapjack" be shorted, perhaps to "fpj"?

**Comment by adf-ncgr** [comment]
I think the idea behind making .div a "child" of 
[species][genotype][assembly] is to indicate that
it has been derived from a specific version of a reference (similar to 
ann files in that respect).

There is the possibility of encoding the situation I think you are 
describing as multiple "derives_from"
relationships in the metadata file, but I don't know how we'd want to 
handle it via naming conventions
(they are so frail...)

**Comment by cann0010** [comment]
"pseudo-assembly of aradu+araip" - since that was to simulate the tetraploid, I think we could call it arahy - and then describe the actual strategy in the README. 
And I don't mind the longer  ".flapjack" suffix. The .vcf and .hmp maybe get shortened by prior convention (at least for vcf certainly).

**Comment by ekcannon** [comment]
Then:
**arahy.arahy.gnm1.div1.Z0Z0.hapmap.hmp
arahy.arahy.gnm1.div1.Z0Z0.flapjack.flapjack**

Or pretend its based on the official arahy assembly:
**arahy.Tifrunner.gnm1.div1.Z0Z0.hapmap.hmp
arahy.Tifrunner.gnm1.div1.Z0Z0.flapjack.flapjack**

?

**Comment by adf-ncgr** [comment]
On 10/23/18 3:46 PM, Steven Cannon wrote:
>
> "pseudo-assembly of aradu+araip" - since that was to simulate the 
> tetraploid, I think we could call it arahy - and then describe the 
> actual strategy in the README.
>
I think this breaks the purpose of the naming; if we call it 
arahy.Tifrunner.gnm1 and it isn't, things will get very confusing. 
Perhaps that isn't exactly what you were suggesting, but we need to 
think through what DSCensor-like applications
(or congruency checkers) are going to do when they hit these weird 
cases. Something programmatic using this file in a context where the 
reference is going to be used  (e.g. to get flanking sequence) will only 
use the README if we agree to make it well-structured metadata (in which 
case congruency checkers will start letting naming conventions slide 
since there will be
no clear mapping for these complex cases).
>
> And I don't mind the longer ".flapjack" suffix. The .vcf and .hmp 
> maybe get shortened by prior convention (at least for vcf
>
> certainly).
>
agreed. I think flapjack installers tend to association .flapjack files 
with the app for ease of use.


adf

**Comment by adf-ncgr** [comment]
On 10/23/18 3:49 PM, ekcannon wrote:
>
> Then:
> *arahy.arahy.gnm1.div1.Z0Z0.hapmap.hmp
> arahy.arahy.gnm1.div1.Z0Z0.flapjack.flapjack*
>
> Or pretend its based on the official arahy assembly:
> *arahy.Tifrunner.gnm1.div1.Z0Z0.hapmap.hmp
> arahy.Tifrunner.gnm1.div1.Z0Z0.flapjack.flapjack*
>
*dear lord NO!!! :)*

**Comment by adf-ncgr** [comment]
PS. what do we want to do about the number following div ?
in the case of maps I think we decided it didn't make sense because:
a) they don't represent versions
b) the "description" (in the second field) serves the uniqifying purpose.

I think a) applies here but we don't seem to have b); in some sense the key
ought to be sufficient for uniqification, although we have opted against 
pulling it
into within-file yuckification schemes for object identifiers 
(sequences, genes).

I'll note that the additional bit of potentially meaningless metadata 
also opens up possibilities for error; see:
https://soybase.org/data/public/Arachis_hypogaea/Tifrunner.rpt3.GZZS/arahy.Tifrunner.rpt1.GZZS.repeats.fna.gz

But, we have been using this sort of sequential numbering in other 
contexts where it doesn't actual mean
versioning; I'm open to leaving it, just want to make sure we all are on 
the same page about it.
And if we use it here maybe we should use it for maps too, just to be 
somewhat consistent (syntactically if not semantically)

**Comment by ekcannon** [comment]
I agree re: the div number. But will removing it break anything with the glyma data? Would the glyma data need to change? As a relatively naive user, I was confused by "div1", "div2", et cetera. The number also obscures the "div" part, at least, for my brain.

I also agree re: Tiffrunner.gnm1. Very bad idea. But how to indicate a "pseudo" assembly? This situation is unlikely to come up ever again.

If I  had my 'druthers:
**arahy.arahy.gnm1.div.Z0Z0.hapmap.hmp**
But I'm still unsure about the data-type field. Are there different classes of genotype data beyond the file format?

**Comment by cann0010** [comment]
Regarding the number following the data type (.div4), I buy the argument that a number should be used for just one purpose (to indicate version), whereas now it is being used for two purposes (version or indicator of processing sequence). Although I have some hesitation about the work of patching so many collections, that feels to me like the better course of action.

Regarding the human-readable description and the suffix: currently the description is all over the map. My preference is that we always include a brief description, that it be meaningful, and that it not merely indicate the data type - where that is accomplished with the suffix. Proposed form for some of the soybean diversity collections (@jd-campbell and @avbrown1 - I'd be willing to tackle the updates if we proceed this way):
`
Wm82.gnm2.div4.G787:                               
glyma.Wm82.gnm2.div4.G787.USB-40x.vcf.gz       glyma.Wm82.gnm2.div.G787.SNPs_USB-40x.vcf
glyma.Wm82.gnm2.div4.G787.USB481.vcf.gz        glyma.Wm82.gnm2.div.G787.SNPs_USB481.vcf
glyma.Wm82.gnm2.div4.G787.USB481_list.txt      glyma.Wm82.gnm2.div.G787.OK
glyma.Wm82.gnm2.div4.G787.USB481_nosoja.vcf.gz glyma.Wm82.gnm2.div.G787.SNPs_USB481_nosoja.vcf
                                                                         
Wm82.gnm2.div6.47GQ:                           
glyma.Wm82.gnm2.div6.47GQ.SNPdata.vcf.gz       glyma.Wm82.gnm2.div.47GQ.SNPs_DESCR.hmp  DESCR: e.g. SNPs_102Canadian
                                                                         
Wm82.gnm2.div7.S3DM:                           
glyma.Wm82.gnm2.div7.S3DM.CultivarList.txt     glyma.Wm82.gnm2.div.S3DM.OK
glyma.Wm82.gnm2.div7.S3DM.SNPdata.vcf.gz       glyma.Wm82.gnm2.div.S3DM.SNPs_DESCR.vcf  
                                                                         
Wm82.gnm2.div8.5KDR:                           
glyma.Wm82.gnm2.div8.5KDR.CultivarList.txt     glyma.Wm82.gnm2.div.5KDR.OK
glyma.Wm82.gnm2.div8.5KDR.SNPdata.hmp.gz       glyma.Wm82.gnm2.div.5KDR.SNPs_DESCR.hmp
glyma.Wm82.gnm2.div8.5KDR.SNPdata.vcf.gz       glyma.Wm82.gnm2.div.5KDR.SNPs_DESCR.vcf
                                                                         
Wm82.gnm2.div9.RW0X:                           
glyma.Wm82.gnm2.div9.RW0X.SNPdata1.vcf.gz      glyma.Wm82.gnm2.div.RW0X.SNPs_DESCR.vcf  DESCR: e.g. pop1 - described in README
glyma.Wm82.gnm2.div9.RW0X.SNPdata2.vcf.gz      glyma.Wm82.gnm2.div.RW0X.SNPs_DESCR.vcf
glyma.Wm82.gnm2.div9.RW0X.SNPdata3.vcf.gz      glyma.Wm82.gnm2.div.RW0X.SNPs_DESCR.vcf
`

**Comment by adf-ncgr** [comment]
this seems like a healthy discussion; I've put an agenda item on today's LIS/PB meeting to see if we can come to a tentative conclusion (even though it's technically more of a LegFed discussion- we can
report back to them on Thursday).

**Comment by ekcannon** [comment]
Possibilities:
**arahy.aradu_araip.gnm1.div.Z0Z0.hapmap.hmp**
**arahy.aradu1_araip1.gnm1.div.Z0Z0.hapmap.hmp**

**Comment by adf-ncgr** [comment]
arahy.aradu1_araip1.gnm1.div.Z0Z0.snp_chip.hmp
?

**Comment by ekcannon** [comment]
Will go with:
**arahy.aradu1_araip1.gnm1.div.Z0Z0.hapmap.hmp**

**Comment by ekcannon** [comment]
Okay, here are the names:
```
  Arachis_hypogaea/arahy.aradu1_araip1.gnm1.div.2B6N.snp_chip.hmp
  Arachis_hypogaea/arahy.aradu1_araip1.gnm1.div.2B6N.snp_chip.flapjack
```
I hesitated on the "arahy" prefix when "aradu" and "araip" are in the file name, but the data is for A. hypogaea even though it's based on the "pseudo" assembly, so will stick with "arahy".

**Comment by adf-ncgr** [comment]
putting under arahy seems to make sense to me, although I'm not sure 
what this would
imply for cross-species alignments to non-pseudo references
(e.g. medicago sativa RNA-seq alignments to M. truncatula genome to call 
SNPs);
but I don't have a better suggestion for this case of the pseudo reference.

Looking at the folder structure now in the data store I think it's 
slightly off the convention used to date:

Arachis_hypogaea/arahy.aradu1_araip1.gnm1.div.2B6N/

should be

Arachis_hypogaea/aradu1_araip1.gnm1.div.2B6N/

with the containing files picking up the arahy. prefix; not claiming to 
love this convention, but to be
consistent I think it should be:

Arachis_hypogaea/Tifrunner.gnm1.KYV3/arahy.Tifrunner.gnm1.KYV3.genome_main.fna.gz
not
Arachis_hypogaea/arahy.Tifrunner.gnm1.KYV3/arahy.Tifrunner.gnm1.KYV3.genome_main.fna.gz

adf

**Comment by ekcannon** [comment]
Thanks for catching this! It was slowly occurring to me while working on the maps, that the species preface on the directories was redundant with the parent directory. This also shortens the directory names.

**Comment by ekcannon** [comment]
See https://github.com/LegumeFederationDataStore/about_the_data_store/blob/master/about_the_Data_Store.md for agreed-upon nomenclature for genotype data.
